ProjectBoujaASP/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication3.ViewModels;

namespace WebApplication3.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;
        public AdminController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole { Name = model.RoleName };
                IdentityResult result = await roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(model);
        }

        // Reste du code
        [HttpGet]
        public IActionResult ListRoles()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }
        // Role ID is passed from the URL to the action
        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            // Find the role by Role ID
            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }
            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };
            // Retrieve all the Users
            foreach (var user in userManager.Users.ToList())
            {
                // If the user is in this role, add the username to
                // Users property of EditRoleViewModel. This model
                // object is then passed to the view for display
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }
            return View(model);
        }
        // This action responds to HttpPost and receives EditRoleViewModel
        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;
                // Update the Role using UpdateAsync
                var result = await roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View(model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View("ListRoles");
            }
        }
        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;
            var role = await roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }
            var model = new List<UserRoleViewModel>();
            foreach (var user in userManager.Users.ToList())
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }
                model.Add(userRoleViewModel);
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }
            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);
                IdentityResult result = null;
                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }
                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new { Id = roleId });
                }
            }
            return RedirectToAction("EditRole", new { Id = roleId });
        }
    }

}

ProjectBoujaASP/Controllers/CategorieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectBoujaASP.Models;
using ProjectBoujaASP.Models.Repositories;

namespace ProjectBoujaASP.Controllers
{
    [Authorize(Roles = "admin,Manager")]

    public class CategorieController : Controller
    {
        readonly ICategorieRepository Categorierepository;
        public CategorieController(ICategorieRepository Categorierepository)
        {
            this.Categorierepository = Categorierepository;
        }
        // GET: CategorieController
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(Categorierepository.GetAll());
        }

        // GET: CategorieController/Details/5
        public ActionResult Details(int id)
        {
            ViewBag.studentcount = Categorierepository.SmartPhoneCount(id);

            var Categorie = Categorierepository.GetById(id);
            return View(Categorie);
        }

        // GET: CategorieController/Create
        //[Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategorieController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize]
        public ActionResult Create(Categorie s)
        {
            try
            {
                Categorierepository.Add(s);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CategorieController/Edit/5
        public ActionResult Edit(int id)
        {
            var Categorie = Categorierepository.GetById(id);
            return View(Categorie);
        }

        // POST: CategorieController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Categorie s)
        {
            try
            {
                Categorierepository.Edit(s);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CategorieController/Delete/5
        public ActionResult Delete(int id)
        {
            var Categorie = Categorierepository.GetById(id);
            return View(Categorie);
        }

        // POST: CategorieController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Categorie s)
        {
            try
            {

                Categorierepository.Delete(s);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjectBoujaASP/Controllers/SmartPhonesController.cs
using ProjectBoujaASP.Models;
using ProjectBoujaASP.Models.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Identity_Test.Controllers
{
    [Authorize(Roles = "admin,Manager")]
    public class SmartPhonesController : Controller
    {
        readonly ICategorieRepository categorieRepository;
        readonly IsmartPhoneRepository smartphoneRepository;

        public SmartPhonesController(IsmartPhoneRepository smartphoneRepository, ICategorieRepository categorieRepository)
        {
            this.smartphoneRepository = smartphoneRepository;
            this.categorieRepository = categorieRepository;
        }
        // GET: SmartPhonesController
        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.CategorieId = new SelectList(smartphoneRepository.GetAll(), "CategorieId", "CategorieName");
            return View(smartphoneRepository.GetAll());
        }

        public ActionResult Search(string name, int? categorieId)
        {
            var result = smartphoneRepository.GetAll();
            if (!string.IsNullOrEmpty(name))
                result = smartphoneRepository.FindByName(name);
            else
            if (categorieId != null)
                result = smartphoneRepository.GetSmartPhonesByCategorieID(categorieId);
            ViewBag.CategorieID = new SelectList(categorieRepository.GetAll(), "CategorieId", "CategorieName");
            return View("Index", result);
        }


        // GET: SmartPhonesController/Details/5
        public ActionResult Details(int id)
        {
            return View(smartphoneRepository.GetById(id));
        }

        // GET: SmartPhonesController/Create

        public ActionResult Create()
        {
            ViewBag.CategorieID = new SelectList(categorieRepository.GetAll(), "CategorieId", "CategorieName");
            return View();
        }

        // POST: SmartPhonesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(SmartPhone s)
        {
            try
            {
                ViewBag.SchoolID = new SelectList(categorieRepository.GetAll(), "CategorieId", "CategorieName", s.CategorieId);
                smartphoneRepository.Add(s);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SmartPhonesController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.CategorieID = new SelectList(categorieRepository.GetAll(), "CategorieId", "CategorieName");
            return View(smartphoneRepository.GetById(id));
        }

        // POST: SmartPhonesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SmartPhone s)
        {
            try
            {
                ViewBag.CategorieID = new SelectList(categorieRepository.GetAll(), "CategorieId", "CategorieName", s.CategorieId);
                smartphoneRepository.Edit(s);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SmartPhonesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(smartphoneRepository.GetById(id));
        }

        // POST: SmartPhonesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(SmartPhone s)
        {
            try
            {
                smartphoneRepository.Delete(s);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjectBoujaASP/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectBoujaASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectBoujaASP.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body style="background-image:url(https://img.freepik.com/free-vector/galaxy-holographic-fantasy-background-pastel-colors_56745-130.jpg?w=2000s)">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="SmartPhones" asp-action="Index" >ProjectBoujaASP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorie" asp-action="index">Categorie <img src= "https://icons.iconarchive.com/icons/sora-meliae/matrilineare/512/Categories-applications-office-icon.png" width="30"> </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SmartPhones" asp-action="index">SmartPhones <img src="https://w7.pngwing.com/pngs/791/868/png-transparent-android-lollipop-computer-software-mobile-phones-lollipop.png" width="30"/></a>
                        </li>
                  
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("admin"))
{
                        <li class="nav-item dropdown font-weight-bold" >
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" ariahaspopup="true" aria-expanded="false">Administration <img src="https://e7.pngegg.com/pngimages/9/763/png-clipart-computer-icons-login-user-system-administrator-admin-desktop-wallpaper-megaphone-thumbnail.png"  width="30"/></a>
                        <div class="dropdown-menu">
                        <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="CreateRole">Create
                        Role <img src= "https://cdn-icons-png.flaticon.com/512/5151/5151145.png" width="30"></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="ListRoles">List
                        Roles <img src= "https://icon-library.com/images/role-icon/role-icon-23.jpg" width="30"></a>
                        </div>
                        </li>
}
                    </ul>
                    <div class="collapse navbar-collapse position: right" id="collapsibleNavbar">
                        <ul class="nav navbar-nav navbar-right">
                        @*If the user is signed-in display Logout link*@
                        @if(SignInManager.IsSignedIn(User))
                        {
                        <li class="btn btn-outline-warning my-2 my-sm-0">
                        <form  class="form-inline my-2 my-lg-0" method="post" asp-controller="account" asp-action="logout">
                        <button type="submit" style="width:auto"
                        class="nav-link btn btn-link py-0">
                        Logout @User.Identity.Name
                         <img src= "https://icons.iconarchive.com/icons/graphicloads/100-flat-2/256/inside-logout-icon.png" width="30"></button>
                        </form>
                        </li>
                        }
                        else
                        {
                        <li class="nav-item ">
                        <a class="btn btn-outline-danger my-2 my-sm-0" asp-controller="Account" asp-action="Register">
                        Register <img src= "https://gurudwaratalhansahib.org/images/icons/register-icon.png" width="30">
                        </a>
                        </li>
                        <li class="nav-item">
                        <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
                        Login <img src= "https://cdn5.vectorstock.com/i/1000x1000/33/09/login-icon-in-trendy-flat-style-vector-20053309.jpg" width="30">
                        </a>
                        </li>
                        }
                        </ul>
                        </div>
                </div>
            </div>
        </nav> 
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
           <b>&copy; 2022 - ProjectBoujaASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></b> 
        
    </footer>
    <script src="~/js/CustomScript.js"></script>
    <script src="~/js/CustomScript.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>